### ISSUE TITLE
Provide a custom dictionary to generate names

### ISSUE THREAD

**Issue by cminardi** [jsonmaur/namor.js#15]
Hi! I'm looking into how to use your library, but I would need to provide a predefined set of nouns and adjectives to generate the names. It looks like the `.rawData` property allows me to read the default dictionary, but not to set it.
If this is correct and I'm not missing anything, would you be open for implementing support for this, or would you allow a PR? Thanks!

**Comment by jsonmaur** [comment]
@cminardi This is now supported in v3.0 :)
